name: abelsberg-2.0-dev
services:
  web:
    build: .
    ports:
      - "127.0.0.1:3001:3000"
    environment:
      - HOSTNAME=0.0.0.0
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:123@database:5436/database_abelsber-2.0
      - AUTH_URL=http://127.0.0.1:3001
      - NEXTAUTH_SECRET=P2FAfG/vbpXELKQ88TTY2UanVypNqiGqFOl1MkhAZ/w=
      - AUTH_TRUST_HOST=true
      - NEXTAUTH_URL=http://127.0.0.1:3001
      # Параметры для разработки
      - NEXT_DISABLE_STATIC_OPTIMIZATION=true
      - NEXT_PUBLIC_VERCEL_ENV=development
      - NEXT_RUNTIME_CACHE_DISABLE=1
    depends_on:
      database:
        condition: service_healthy
    networks:
      - project-network
    restart: always

  database:
    image: postgres:16.1-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: "123"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "database_abelsber-2.0"
    ports:
     - "127.0.0.1:5436:5432"
    volumes:
      - ./data/abelsber-2.0:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - project-network

networks:
  project-network:
    driver: bridge
