// import { SectionsProvider } from "@/contexts/SectionsContext"
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Inter } from 'next/font/google';

import "./globals.css";
import { SectionsProvider } from './admin/contexts/SectionsContext'
import { getBathroomPageData } from "@/db/bathroom"

const inter = Inter({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-inter',
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const data = await getBathroomPageData()

  const initialData = {
    banner: data.banner,
    sections: data.sections.map(section => ({
      id: section.id,
      title: section.title,
      description: section.description,
      linkText: section.link.text,
      linkUrl: section.link.url,
      order: section.order,
      createdAt: null,
      updatedAt: null,
      images: section.images.map((img, index) => ({
        id: index + 1,
        src: img.src,
        alt: img.alt,
        order: img.order,
        sectionId: null,
        collectionId: null,
        createdAt: null,
        updatedAt: null
      }))
    })),
    collections: data.collections
  }

  return (
    <html lang="en" className={inter.variable}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SectionsProvider initialData={initialData}>
          {children}
        </SectionsProvider>
      </body>
    </html>
  );
}
